// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

// import { ToastContainer } from 'react-toastify';
// import 'react-toastify/dist/ReactToastify.css'; // Import the CSS for toast styles
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         {children}
//         <ToastContainer 
//           position="top-right" 
//           autoClose={3000} 
//           hideProgressBar={false}
//           newestOnTop={false}
//           closeOnClick
//           rtl={false}
//           pauseOnFocusLoss
//           draggable
//           pauseOnHover
//           theme="light"
//         />
//       </body>
//     </html>
//   );
// }


// "use client";

// import { usePathname } from "next/navigation";
// import { useEffect } from "react";
// import { Inter } from "next/font/google";
// import { SessionProvider } from "next-auth/react";
// import { io } from "socket.io-client";
// import FloatingChatButton from "./components/FloatingChatButton";
// import "./globals.css";
// import { Toaster } from "react-hot-toast"; // ✅ Use Toaster from react-hot-toast

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({ children }) {
//   const pathname = usePathname();

//   useEffect(() => {
//     const socket = io("http://localhost:3001");
//     socket.on("connect", () => console.log("Connected to WebSocket server"));
//     return () => {
//       socket.disconnect();
//     };
//   }, []);

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <SessionProvider>
//           <Toaster position="top-right" reverseOrder={false} /> {/* ✅ Use react-hot-toast Toaster */}
//           {children}
//           {pathname === "/home" && <FloatingChatButton />}
//         </SessionProvider>
//       </body>
//     </html>
//   );
// }


import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import ProvidersWrapper from "./providers"; // ✅ new name to avoid confusion
import FloatingChatWrapper from "./components/FloatingChatWrapper"; // 👇 Create a wrapper to handle path check
import GlobalSpeechAssistant from "./components/GlobalSpeechAssistant";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Campus Connection",
  description: "Your college network, reimagined.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProvidersWrapper>
          <Toaster position="top-right" reverseOrder={false} />
                <Toaster position="top-center" reverseOrder={false} />
          
          {children}
          <FloatingChatWrapper /> {/* 🟢 now it's a client-safe wrapper */}
          {/* {pathname !== "/group-members" && <GlobalSpeechAssistant />} */}
          <GlobalSpeechAssistant />
        </ProvidersWrapper>
      </body>
    </html>
  );
}
